M48
; DRILL file {KiCad 8.0.6} date 2024-11-27T03:53:47-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-11-27T03:53:47-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X186.364Y-145.288
T2
X181.864Y-145.288
M30
